### ISSUE TITLE
Viewer should show morph target names

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/playcanvas-viewer#106]
Morph target in the engine stores its name in MorphTarget.name, and the viewer would ideally display it instead of just the 
index.

![Screen Shot 2021-03-29 at 1 21 55 PM](https://user-images.githubusercontent.com/59932779/112835881-c6820700-9091-11eb-8992-f6fd129f69bc.png)

**Comment by slimbuck** [comment]
Fixed in #130
