### ISSUE TITLE
Kenney model GLBs don't load correctly

### ISSUE THREAD

**Issue by yaustar** [playcanvas/playcanvas-viewer#124]
Forum thread: https://forum.playcanvas.com/t/glb-asset-doesnt-load/21486

Example asset: 
[ambulance.glb.zip](https://github.com/playcanvas/playcanvas-viewer/files/7001802/ambulance.glb.zip)

Works in Babylon: 
![image](https://user-images.githubusercontent.com/16639049/129771012-bd7fa20c-ed79-42b7-ace3-2df50ce832b7.png)

Worth noting that no textures are are used in Kenney's assets

**Comment by slimbuck** [comment]
Not sure why this wasn't working, bug latest engine loads and renders this model fine.

Updated viewer will go out soon.

**Comment by yaustar** [comment]
Viewer has been updated and published

![image](https://user-images.githubusercontent.com/16639049/129882508-2904b6f7-4caf-4f58-9304-1f51e8e12755.png)
