### ISSUE TITLE
Some meshopt-compressed models not displayed

### ISSUE THREAD

**Issue by donmccurdy** [playcanvas/playcanvas-viewer#125]
I've written an alternative encoder for the `EXT_meshopt_compression` glTF extension using [glTF-Transform](gltf-transform.donmccurdy.com/) and the [meshoptimizer](https://www.npmjs.com/package/meshoptimizer) library (rather than the original gltfpack CLI tool). Currently it supports the moderate-compression meshopt mode (similar to gltfpack's `-c` mode) but not the higher-compression mode (gltfpack's `-cc`) yet. For that reason gltfpack will currently give better compression, but I'm planning to fix the remaining issues. One possible use of this would be to support applying meshopt compression in a web browser.

Testing the output of my tool on the PlayCanvas viewer, I'm finding that the model does not appear on screen. The same models work correctly in the three.js and babylon.js viewers, so I think perhaps this is a bug in this viewer? Note that my implementation of quantization is a bit different from gltfpack's, perhaps that has some effect on the viewer's chosen viewport. I've tried compressing the same models with gltfpack — they displayed fine — so it's possible this is a bug in my encoder, but given that the files do work in ~3 other tools I think it is more likely to be a PlayCanvas viewer bug.

Attached:

- `SH.glb` Model using `KHR_mesh_quantization` + `EXT_meshopt_compression` + skinning
- `SH_QUANT.glb` Same model, using `KHR_mesh_quantization` + skinning
- `Matilda.glb` Model using `KHR_mesh_quantization` + `EXT_meshopt_compression`, no animation

[Archive.zip](https://github.com/playcanvas/playcanvas-viewer/files/7051112/Archive.zip)

The `SH_QUANT` example using _just_ skinning (no meshopt compression) also has apparent skinning issues, so it's possible part of the issue is related to `KHR_mesh_quantization`, which meshopt compression requires for best results. The original (unquantized) version works in PlayCanvas fine.

**Comment by slimbuck** [comment]
Hi @donmccurdy, the `POSITION` accessors in the compressed glbs have been flagged as normalized. If I ignore the flag for position accessor then Matilda.glb appears to load fine.

Is the normalized flag on `POSITION` correct/intentional?

**Comment by donmccurdy** [comment]
Use of "normalized=true" is intentional, but not required by the extension, and I think gltfpack makes a different choice than I did here. The quantization-only version uses normalized POSITION values too.

If you use accessor min/max to compute mesh bounds, note that these store raw values and not [-1,1] values.

I'll see if I can make a test that mixes these options in the same file, that might tell us if the issue is related to the viewport or the geometry...

**Comment by slimbuck** [comment]
Hi @donmccurdy, I found the issue. We weren't correctly calculating the bounding box of bones on a mesh with normalized position data. This has been addressed in https://github.com/playcanvas/engine/pull/3431.

Thanks again for the bug report and repo!
