### ISSUE TITLE
When viewing an animation, allow the user to render the skeleton 

### ISSUE THREAD

**Issue by yaustar** [playcanvas/playcanvas-viewer#129]
This is to make it easier to debug animations when played in the engine

**Comment by slimbuck** [comment]
do you need anything different to the 'skeleton' option under SHOW?

**Comment by yaustar** [comment]
That doesn't seem to work at the moment? It only works when there is a mesh/model to be rendered.

In this use case, we just have the animation file from importing into PlayCanvas Editor

https://user-images.githubusercontent.com/16639049/133972571-f1c5862b-30b2-4c74-9b41-f132770da6b0.mp4

**Comment by slimbuck** [comment]
Ahh interesting. This used to work!

**Comment by yaustar** [comment]
![image](https://user-images.githubusercontent.com/16639049/149322363-e2c8db3e-7710-4167-85ec-05a194e1cf34.png)
