### ISSUE TITLE
Animation scrubber bar does not appear on smaller screensizes

### ISSUE THREAD

**Issue by matteobartaliniSC** [playcanvas/playcanvas-viewer#281]
For our use case, we are using the playcanvas model viewer on a split window. When using the viewer in a split window, several of the UI elements get hidden. Mostly importantly the animation scrubber: 
![image](https://github.com/playcanvas/model-viewer/assets/102549234/d0faaa54-b63f-476b-87dd-df7f72b6c6eb)

Can the animation scrubber be shown even on smaller window sizes?

**Comment by mvaligursky** [comment]
on less wide screen, this is currently displayed for reference - so the animation controls are missing:

<img width="542" alt="Screenshot 2024-02-06 at 16 44 26" src="https://github.com/playcanvas/model-viewer/assets/59932779/d59e79dd-d418-4659-9687-6bfdfd170383">
