### ISSUE TITLE
Viewer does not resize correctly

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/playcanvas-viewer#3]
* Camera aspect ratio does not update
* Left panel flickers

![resize](https://user-images.githubusercontent.com/697563/87661056-e79b0580-c757-11ea-867f-5aec88a6165d.gif)

**Comment by slimbuck** [comment]
Is this Chrome on windows? Chrome on mac works fine...

**Comment by slimbuck** [comment]
If possible could you upgrade your Windows to Mac? kthxbye

**Comment by willeastcott** [comment]
Yes, Chrome on Windows 10.

**Comment by slimbuck** [comment]
I haven't managed to repro this on Windows Chrome.

**Comment by slimbuck** [comment]
Sorry wrong ticket. I have repro'd resizing issue, but not widgets issue.

**Comment by willeastcott** [comment]
Widgets issue could be related to #4
