### ISSUE TITLE
Checkboxes not visible in Windows Chrome

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/playcanvas-viewer#4]
![image](https://user-images.githubusercontent.com/697563/87661225-2af57400-c758-11ea-9c25-f6268cc5ea52.png)

![image](https://user-images.githubusercontent.com/697563/87661162-15804a00-c758-11ea-8fa0-ac4eadcc1ca9.png)

**Comment by willeastcott** [comment]
If I remove this line from `style.css`, it works:

```
    appearance: none;
```

![image](https://user-images.githubusercontent.com/697563/87730835-d1755f80-c7c0-11ea-9c66-c05cf4e01f40.png)

**Comment by slimbuck** [comment]
Interesting. I managed to repro this issue yesterday after upgrading chrome on my Windows machine from v83->84. Presumably as the new version rolls out everyone will start seeing the same issue.
