### ISSUE TITLE
Allow pain-free viewer/engine local dev

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/playcanvas-viewer#41]
It is a pain using the viewer with a local build of the engine, especially since loosing `use_local_engine`.

Using the viewer with local engine currently requires the following:
- create symlink in playcanvas_viewer to ../engine/build/playcanvas.js and ../engine/build/playcanvas-extras.js
- replace `import blah from 'playcanvas'` to `import blah from 'playcanvas.js'` in viewer.js, controls.js and index.js

This is a huge pain and we need a solution ideally integrated with webpack.

**Comment by mvaligursky** [comment]
I really look forward to this.
