### ISSUE TITLE
Autoplay animation on load

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/playcanvas-viewer#44]
Currently, animated glTF scenes will not auto-play their animation(s):

![image](https://user-images.githubusercontent.com/697563/89593091-319e7500-d846-11ea-8b47-78ec1c8542a0.png)

**Comment by slimbuck** [comment]
I am thinking that by default the viewer should play all the loaded animations in turn, one after the other. How does that sound?

**Comment by willeastcott** [comment]
Sounds reasonable. Better than what we have now. 😄

**Comment by slimbuck** [comment]
This was resolved in #50
