### ISSUE TITLE
Shift drag is not an obvious feature. Can we add a Open/Add button as well?

### ISSUE THREAD

**Issue by yaustar** [playcanvas/playcanvas-viewer#46]
The shift drag to add multiple GLBs is not an obvious feature to the user. Could we add some sort of UI for this as well?

**Comment by kungfooman** [comment]
And playcanvas-gltf uses `Drag/Ctrl/Drop` instead of `Drag/Shift/Drop`

**Comment by slimbuck** [comment]
Closing in favour of dup https://github.com/playcanvas/playcanvas-viewer/issues/64
