### ISSUE TITLE
Animation with STEP interpolation on scale not displayed

### ISSUE THREAD

**Issue by donmccurdy** [playcanvas/playcanvas-viewer#55]
[SuzanneSequence.glb.zip](https://github.com/playcanvas/playcanvas-viewer/files/5127465/SuzanneSequence.glb.zip)

This example should step through a sequence of 5 meshes, displaying each at scale 1,1,1 for 1/2 second before hiding it with scale 0,0,0 and displaying the next mesh. The example is simple (modeled in Blender, animated with glTF-Transform) but would be similar to more complex animation from programs like Quill.

The model doesn't seem to animate in the PlayCanvas viewer currently. The result should be:

![BBC4AED3-21F3-4244-933C-2ECBBFA2B744-2877-000119D9A79ADF7C](https://user-images.githubusercontent.com/1848368/91252859-466a7c00-e713-11ea-87d9-cc499d36559a.gif)

Aside, but minor — the model doesn't include normals, and so should be displayed with flat normals rather than smooth ideally.

**Comment by slimbuck** [comment]
Thanks for this @donmccurdy!

**Comment by ellthompson** [comment]
Fixed in playcanvas/engine#2401
