### ISSUE TITLE
Browse model hierarchy

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/playcanvas-viewer#61]
It would be great if it was possible to browse the model hierarchy directly in the viewer.

Ideally we could see:
- the node hierarchy including name, position, rotation, scale
- mesh details including #vert, #primitives
- material details including basic settings and textures
- texture details possibly with preview
- animation details
- etc

**Comment by slimbuck** [comment]
Partly complete in https://github.com/playcanvas/playcanvas-viewer/pull/102

**Comment by willeastcott** [comment]
The majority of this is now implemented. I would suggest closing this and opening new, specific feature requests for anything outstanding.
