### ISSUE TITLE
Add an upload button for files and background

### ISSUE THREAD

**Issue by WaelShaikh** [playcanvas/playcanvas-viewer#64]
Currently the viewer is unusable on phones as the only option to open files is via drag and drop which is not possible on mobile devices. An upload button would be really helpful for mobile users as the rest of the UI already does work perfectly on phones.

**Comment by yak32** [comment]
https://github.com/playcanvas/playcanvas-viewer/pull/104

**Comment by yaustar** [comment]
Been added
