### ISSUE TITLE
How to load multi file assets?

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/playcanvas-viewer#7]
I am not sure how the API is supposed to work:

```js
viewer.load([
"http://127.0.0.1/libwebgame_assets/gltf/AppleTree/AppleTree.gltf",
"http://127.0.0.1/libwebgame_assets/gltf/AppleTree/AppleTree.bin"
]);
```

The AppleTree got these files:

![image](https://user-images.githubusercontent.com/5236548/87761391-abc47680-c811-11ea-89de-ff398d85ada5.png)

Result:

`playcanvas.js:24239 failed to load uri=AppleTree.bin`

![image](https://user-images.githubusercontent.com/5236548/87761472-d0b8e980-c811-11ea-8d71-cc7cb68b5ffa.png)

**Comment by slimbuck** [comment]
Hi @kungfooman ,

Try specifying the files as objects with url and filename properties. The filename is used to match internal references. Check out the drop handler.

Hope that helps!

**Comment by kungfooman** [comment]
Hi @slimbuck, thanks for the info!

Got it working like this now:

```js
viewer.load([{
    url: "http://127.0.0.1/libwebgame_assets/gltf/AppleTree/AppleTree.gltf",
    filename: "AppleTree.gltf"
}, {
    url: "http://127.0.0.1/libwebgame_assets/gltf/AppleTree/AppleTree.bin",
    filename: "AppleTree.bin",
}, {
    url: "http://127.0.0.1/libwebgame_assets/gltf/AppleTree/AppleTree_baseColor.png",
    filename: "AppleTree_baseColor.png",
}, {
    url: "http://127.0.0.1/libwebgame_assets/gltf/AppleTree/AppleTree_roughnessMetallic.png",
    filename: "AppleTree_roughnessMetallic.png",
}, {
    url: "http://127.0.0.1/libwebgame_assets/gltf/AppleTree/AppleTree_normal.png",
    filename: "AppleTree_normal.png",
}, {
    url: "http://127.0.0.1/libwebgame_assets/gltf/AppleTree/AppleTree_baseColor1.png",
    filename: "AppleTree_baseColor1.png",
}, {
    url: "http://127.0.0.1/libwebgame_assets/gltf/AppleTree/AppleTree_roughnessMetallic1.png",
    filename: "AppleTree_roughnessMetallic1.png",
}, {
    url: "http://127.0.0.1/libwebgame_assets/gltf/AppleTree/AppleTree_normal1.png",
    filename: "AppleTree_normal1.png",
}, {
    url: "http://127.0.0.1/libwebgame_assets/gltf/AppleTree/AppleTree_baseColor2.png",
    filename: "AppleTree_baseColor2.png",
}, {
    url: "http://127.0.0.1/libwebgame_assets/gltf/AppleTree/AppleTree_roughnessMetallic2.png",
    filename: "AppleTree_roughnessMetallic2.png",
}, {
    url: "http://127.0.0.1/libwebgame_assets/gltf/AppleTree/AppleTree_normal2.png",
    filename: "AppleTree_normal2.png",
}]);
```

Isn't it a bit strange that people have to reference every single file? In playcanvas-gltf people only have to define `basePath` (which even can be derived from a single URL in lots of cases)

**Comment by slimbuck** [comment]
Hi @kungfooman,

The next release of the viewer is a big change which includes the ability to load a gltf using its URL alone. The basePath is derived from the URL though, it can't be specified.

Hope this helps!

**Comment by willeastcott** [comment]
I think this is now supported, right? So we can close this?

**Comment by kungfooman** [comment]
Just built HEAD and it doesn't work with `Viewer#load` at least:

![image](https://user-images.githubusercontent.com/5236548/88475371-70bbf480-cf2f-11ea-9087-7deb0fa9b419.png)

**Comment by willeastcott** [comment]
How are you even able to see `viewer` using the latest codebase?

![image](https://user-images.githubusercontent.com/697563/88475670-02286800-cf2a-11ea-9233-5e1fd48b6da1.png)

Now that the viewer is built with Webpack, that variable is not visible from the JS console.

**Comment by kungfooman** [comment]
```js
window.pc = pc;

function startViewer() {
    var viewer = new Viewer(document.getElementById("application-canvas"), onSceneReset, onAnimationsLoaded, onMorphTargetsLoaded);
    registerElementEvents(viewer);
    window.viewer = viewer;
}
```

**Comment by willeastcott** [comment]
Ah ok, so you've exposed the variable yourself. I also see the problem now:

![image](https://user-images.githubusercontent.com/697563/88476205-985e8d00-cf2e-11ea-887d-eb9b3a266cde.png)

Looks like dependencies aren't loaded for unpacked glTF scenes still. I think it's best to wait for @slimbuck to comment.

**Comment by slimbuck** [comment]
Hi @kungfooman, @willeastcott,

This will work correctly once the next version of engine has been released, as it requires https://github.com/playcanvas/engine/pull/2312.

Thanks!

**Comment by slimbuck** [comment]
https://github.com/playcanvas/engine/releases/tag/v1.32.3

This should now be fixed! (Please reopen if you any further issues).
