### ISSUE TITLE
Missing deps: bfj and ejs-webpack-loader

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/playcanvas-viewer#97]
I had to install `bfj` and `ejs-webpack-loader` manually, otherwise I would run into these two errors:

![image](https://user-images.githubusercontent.com/5236548/109671199-29a47a80-7b74-11eb-8946-8bca5beb2c3b.png)

![image](https://user-images.githubusercontent.com/5236548/109671270-388b2d00-7b74-11eb-9619-e9e9960d66e7.png)

I don't know why others don't seem to have an issue with this, but maybe add it to `package.json`?

**Comment by slimbuck** [comment]
Hi @kungfooman,

Are you getting this issue? I just tried deleting ./node_modules, did `npm install` and `npm build` and it worked fine for me.

I'm on npm 6.14.4 and node v10.20.1.

Thanks!

**Comment by kungfooman** [comment]
Just tried again and it works here aswell now 🌈 

I'm on npm 7.0.3 and node v15.0.1.
