### ISSUE TITLE
Cloning animated models doesn't work

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/playcanvas-viewer#99]
I tried it very simply with:

```js
clone = viewer.entities[0].clone()
viewer.app.root.addChild(clone)
clone.translate(1, 0, 0)
clone.anim.playing
```

Anything I'm doing wrong? The second model is just not animated, even though all properties seem right.

![image](https://user-images.githubusercontent.com/5236548/109964246-b7f03c00-7ced-11eb-9e61-f809b9a6fc8d.png)

**Comment by mvaligursky** [comment]
I'm assigning this to @ellthompson to investigate. When the entity set up for animation is cloned, it should be able to play the animation. This would be great to add as a test to some animation engine example perhaps as well.

**Comment by yaustar** [comment]
Looks like if the stategraph is built in code (as done via the viewer here https://github.com/playcanvas/playcanvas-viewer/blob/4b2868ef938db592c358685f6b3c130ec73c0716/src/viewer.ts#L1202), cloning the component doesn't clone or reference that data.

**Comment by kungfooman** [comment]
I tried this with latest engine and viewer and I still can't get it to work, anyone else tested this?

**Comment by yaustar** [comment]
The PR has been merged to master but hasn't been released to stable yet (IE not been through our test plan etc)

**Comment by kungfooman** [comment]
> The PR has been merged to master but hasn't been released to stable yet (IE not been through our test plan etc)
> 
> When you say tested with latest engine, are you testing against master or stable version of the engine?

Thanks for quick response!

I tried with `npm run local`, which is using latest engine:

```js
"local": "cross-env ENGINE_PATH=../playcanvas-engine/build/playcanvas.js EXTRAS_PATH=../playcanvas-engine/build/playcanvas-extras.js concurrently --kill-others \"npm run build:watch\" \"npm run serve\"",
```

`e.anim.system.cloneComponent` in devtools also shows me the latest code (just for double-checking):

![image](https://user-images.githubusercontent.com/5236548/123517639-702d6000-d6a2-11eb-8785-4fd3cd125f50.png)

And I added `debugger;` just to see what's going on - didn't figure anything out yet 😅

**Comment by yaustar** [comment]
The npm modules are always the stable version so it still hasn't got the fix from the PR.

The next release with this fix would be in v1.44.0

**Comment by yaustar** [comment]
Hm.. All the data and information is available in the clone, wondering if this is a viewer or engine issue right now 🤔

**Comment by kungfooman** [comment]
Thanks a lot for all pointers @yaustar 

I dived in a little bit more with your information, starting from this code (basically e=original, ee=clone):

```js
e = viewer.entities[0];
ee = e.clone()
viewer.app.root.addChild(ee)
ee.translate(1, 0, 0)
ee.anim.playing
```

The clone is lacking the targets `e.anim._layers[0]._controller._animEvaluator._targets`:

![image](https://user-images.githubusercontent.com/5236548/123537528-2be8a100-d730-11eb-9254-31fd186991a7.png)

I found the `rebind` method, but the animation still doesn't work after calling it:

![image](https://user-images.githubusercontent.com/5236548/123537580-7538f080-d730-11eb-88f3-d82db000f979.png)

Then, in a "fresh" scene, I found some `NaN`'s:

![image](https://user-images.githubusercontent.com/5236548/123537667-f42e2900-d730-11eb-8b28-87422f61e9ab.png)

If this `NaN` curves number is used inside a loop, it will basically never do anything (all comparisons are false).

Might be an artifact generated of two things called `target` and mixing them up:

![image](https://user-images.githubusercontent.com/5236548/123537792-99490180-d731-11eb-8d7f-701de13d19a4.png)

While `class AnimTarget` has no curves: https://github.com/playcanvas/engine/blob/master/src/anim/evaluator/anim-target.js

**Comment by yaustar** [comment]
@kungfooman We are looking at the issue and looks like it be a bigger thing to handle and needs discussion with the wider team.

Work around is to call .rebind() on the anim component after the clone:

```
cloneEntity.anim.rebind();
```

**Comment by kungfooman** [comment]
Thanks for the response @yaustar 

Looking forward to when it works after team discussion, I just tried your suggestion to call `AnimComponent#rebind`, which doesn't work for me at least:

![image](https://user-images.githubusercontent.com/5236548/123650740-28861000-d82b-11eb-8cd4-e645a82f4a79.png)

**Comment by yaustar** [comment]
Is that on latest engine? Can you send me that model/anim that you are using please?

**Comment by kungfooman** [comment]
I just pulled latest changes again and rebuild (added console.log to see it is actually using latest changes):

![image](https://user-images.githubusercontent.com/5236548/123653262-481e3800-d82d-11eb-9d92-52e209fe55c4.png)

I don't know which test model you mean, could you link it as well?

This is the SambaDancing model, no clue who owns it (kinda used for testing often): 
[SambaDancing.zip](https://github.com/playcanvas/playcanvas-viewer/files/6727038/SambaDancing.zip)

**Comment by yaustar** [comment]
Thanks, we used this one: https://github.com/cx20/gltf-test/tree/master/sampleModels/BoxAnimated/glTF-Binary

**Comment by kungfooman** [comment]
Thanks, I can confirm, that one works for me as well, couldn't get any other animated model to work (more complex ones with skinned meshes and many bones)

**Comment by yaustar** [comment]
It's probably worth noting you shouldn't have this issue with a Model Component and Anim Component combo. It's only the newer Render Component and Anim Component combination that has this issue at the moment

**Comment by ellthompson** [comment]
Hi @kungfooman, it looks like the issue with cloning an entity with a render component and anim component is now isolated to the viewer. It's likely because the viewer has a specific code path for single entity that's loaded into it.

I've tested cloning in this project and it's working ok: https://playcanvas.com/project/808975/overview/renderanimtest
(Note that the launch page will require a use_local_engine url param as the latest clone changes are yet to be released)

**Comment by mvaligursky** [comment]
@ellthompson - any update on this please? I'd be great to figure out, considering we're switching to render/anim component as the recommended path.

**Comment by kungfooman** [comment]
I don't know which commit fixed it, but its working now:

![image](https://user-images.githubusercontent.com/5236548/136186256-9531c97c-ea93-417e-9662-ebefec65987e.png)


Code to spawn 8x8 models and playing random animations on them:

```js

function spawn8x8(s = 2) {
	var clones = [];
	for (var i=0; i<8; i++) {
		for (var j=0; j<8; j++) {
			var ee = viewer.entities[0].clone();
			clones.push(ee);
			ee.translate(j * s, 0, i * s);
			viewer.app.root.addChild(ee)
		}
	}
	return clones;
}

clones = spawn8x8();

function playRandomAnimation(entity) {
  var layer = entity.anim.layers[0];
  var states = layer.states;
  var randomState = states[Math.trunc(Math.random() * states.length)];
  layer.play(randomState);
  return randomState;
}

clones.map(playRandomAnimation);
```
